apiVersion: v1
data:
  secret_key_base: YzcwZTYyODdhYmIzNjE1NzI4MjkwYTA1ZjNmZDlkM2NlYWU2NzIzNGY0ZDFlYTc2OTQyODFkOTM0MTczNWEwYzA0NWEzYjAxZGVkMDEyYjBhODQxNzhmNDAxMjY2OTA2ZDJjMDM2ZTY3MWQ1MzZkNDZhZDhiZGVlOGEwYjQ5ODY=
  mysql_password: bXkgc2VjdXJlIHBhc3N3b3Jk
  mysql_user: cm9vdA==
kind: Secret
type: Opaque
metadata:
  name: app-secrets
